[FileDialog]
history=file:///home/abu/python-projects/css-test, file:///home/abu/python-projects/myblog/blog, file:///home/abu/codequest/race-ms, file:///home/abu/codequest/race-ms/database, file:///home/abu/Downloads
lastVisited=file:///home/abu/Downloads
qtVersion=6.4.3
shortcuts=file:, file:///home/abu
sidebarWidth=84
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xb8\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xe8\0\0\0\x1\0\0\0\0\0\0\0\x36\0\0\0\x1\0\0\0\0\0\0\0:\0\0\0\x1\0\0\0\0\0\0\0`\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)
viewMode=Detail
