#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

~/.config/polybar/launch.sh

nitrogen --restore &
picom -b &
libinput-gestures-setup autostart start &
setxkbmap -option grp:caps_toggle us,ru &
