[app]
appFont=Open Sans
appFontSize=11
darkMode=Auto
darkModeOn=false
disableProxyForRedisConnections=false
extensionServerPassword=
extensionServerRequestTimeout=10
extensionServerUrl=
extensionServerUser=
liveUpdateInterval=10
liveUpdateKeysLimit=1000
locale=system
namespacedKeysShortName=true
reopenNamespacesOnReload=true
scanLimit=10000
showNamespacesOnTop=false
treeItemMaxChilds=1000
useSystemProxy=false
valueEditorFont=Ubuntu Mono
valueEditorFontSize=11
valueEditorPageSize=100
valueSizeLimit=150000

[formatters]
formatters=@Invalid()

[windows_settings]
height=1044
splitView=@ByteArray(\x81\xa2\x65index\0npreferredWidth\xfb@[\xc0\0\0\0\0\0)
width=990
